dev:
	ng build --configuration development --subresource-integrity

prod: 
	ng build --configuration production --subresource-integrity

mobile_dev:
	ng build --configuration mobile-development --subresource-integrity

mobile_prod:
	ng build --configuration mobile-production --subresource-integrity