services:
  frontend:
    container_name: frontend
    user: "101:101"
    image: ghcr.io/seaweedbraincy/zero-totp-frontend:dev

  api:
    container_name: api
    image: ghcr.io/seaweedbraincy/zero-totp-api:dev
    command: ./start.sh auto-upgrade
    user: "101:101"
    volumes:
      - ./zero-totp/config/:/api/config/
      - ./secret:/api/secret
      #- ./zero-totp-logs:/var/log/api
    depends_on:
      - database
    restart: always
  database:
    environment:
      MYSQL_ROOT_PASSWORD: tmppassword
      MYSQL_DATABASE: zero_totp
      MYSQL_USER: api
      MYSQL_PASSWORD: tmppassword
    image:  mariadb:latest
    container_name: database


  caddy: 
    container_name: caddy
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - api
