"""add session token table

Revision ID: 0ba349cab310
Revises: 9e958eb5226a
Create Date: 2024-11-17 22:47:46.695823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ba349cab310'
down_revision: Union[str, None] = '9e958eb5226a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_token',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.String(length=20), nullable=False),
    sa.Column('revoke_timestamp', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('refresh_token', sa.Column('session_token_id', sa.String(length=36), nullable=False))
    op.drop_column('refresh_token', 'jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('jti', mysql.VARCHAR(length=36), nullable=False))
    op.drop_column('refresh_token', 'session_token_id')
    op.drop_table('session_token')
    # ### end Alembic commands ###
