"""Add ratelimiting table

Revision ID: 443cb54f4166
Revises: 
Create Date: 2024-01-22 15:45:22.866096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443cb54f4166'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hashed', sa.Text(), nullable=False),
    sa.Column('token_expiration', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enc_credentials', sa.Text(), nullable=False),
    sa.Column('cipher_nonce', sa.Text(), nullable=False),
    sa.Column('cipher_tag', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favicon_preview_policy', sa.String(length=256), nullable=True),
    sa.Column('derivation_iteration', sa.Integer(), nullable=True),
    sa.Column('minimum_backup_kept', sa.Integer(), nullable=True),
    sa.Column('backup_lifetime', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limiting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('totp_secret_enc',
    sa.Column('uuid', sa.String(length=256), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('totp_secret_enc')
    op.drop_table('rate_limiting')
    op.drop_table('preferences')
    op.drop_table('oauth_tokens')
    op.drop_table('admin_tokens')
    # ### end Alembic commands ###
