"""Add upgradeConfiguration table

Revision ID: 7d0ea0be6a80
Revises: fdbb247ab912
Create Date: 2025-01-31 18:59:25.277579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0ea0be6a80'
down_revision: Union[str, None] = 'fdbb247ab912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('backup_max_age_days', sa.Integer(), nullable=False),
    sa.Column('backup_minimum_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_configuration')
    # ### end Alembic commands ###
