"""Allow ip to be null

Revision ID: 8a48940b2843
Revises: 443cb54f4166
Create Date: 2024-01-22 16:50:30.602500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a48940b2843'
down_revision = '443cb54f4166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_limiting', schema=None) as batch_op:
        batch_op.alter_column('ip',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_limiting', schema=None) as batch_op:
        batch_op.alter_column('ip',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)

    # ### end Alembic commands ###
