"""v2.2.1 Add Session table

Revision ID: 916ea1298ccb
Revises: 7d0ea0be6a80
Create Date: 2025-11-12 00:22:09.659342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916ea1298ccb'
down_revision: Union[str, None] = '7d0ea0be6a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_user_agent', sa.String(length=512), nullable=True),
    sa.Column('encrypted_device_name', sa.String(length=256), nullable=True),
    sa.Column('encrypted_platform', sa.String(length=256), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.String(length=20), nullable=False),
    sa.Column('last_active_at', sa.String(length=20), nullable=False),
    sa.Column('expiration_timestamp', sa.String(length=20), nullable=False),
    sa.Column('revoke_timestamp', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='fk_session_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('refresh_token', sa.Column('session_id', sa.String(length=36), nullable=False))
    op.create_foreign_key('fk_refresh_token_session_id', 'refresh_token', 'session', ['session_id'], ['id'])
    op.add_column('session_token', sa.Column('session_id', sa.String(length=36), nullable=False))
    op.create_foreign_key('fk_session_token_session_id', 'session_token', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_session_token_session_id', 'session_token', type_='foreignkey')
    op.drop_column('session_token', 'session_id')
    op.drop_constraint('fk_refresh_token_session_id', 'refresh_token', type_='foreignkey')
    op.drop_column('refresh_token', 'session_id')
    op.drop_table('session')
    # ### end Alembic commands ###
