"""add refresh token table

Revision ID: 9e958eb5226a
Revises: cb842f70475a
Create Date: 2024-10-24 14:06:42.875047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e958eb5226a'
down_revision: Union[str, None] = 'cb842f70475a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_token', sa.String(length=64), nullable=False),
    sa.Column('expiration', sa.String(length=20), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('revoke_timestamp', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
