"""add vault autolock delay preference

Revision ID: cb842f70475a
Revises: 87dd4a4e3a58
Create Date: 2024-10-06 17:31:25.824596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb842f70475a'
down_revision: Union[str, None] = '87dd4a4e3a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('vault_autolock_delay_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'vault_autolock_delay_min')
    # ### end Alembic commands ###
