"""Upgrade to db-v2.3.0

Revision ID: ce20accd15e0
Revises: 916ea1298ccb
Create Date: 2025-12-28 17:43:20.362081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce20accd15e0'
down_revision: Union[str, None] = '916ea1298ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ZKE_encryption_key_ibfk_1'), 'ZKE_encryption_key', type_='foreignkey')
    op.create_foreign_key('fk_zke_encryption_key_user_id', 'ZKE_encryption_key', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('backup_configuration_ibfk_1'), 'backup_configuration', type_='foreignkey')
    op.create_foreign_key('fk_backup_configuration_user_id', 'backup_configuration', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('email_verification_token_ibfk_1'), 'email_verification_token', type_='foreignkey')
    op.create_foreign_key('fk_email_verification_token_user_id', 'email_verification_token', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('google_drive_integration_ibfk_1'), 'google_drive_integration', type_='foreignkey')
    op.create_foreign_key('fk_google_drive_integration_user_id', 'google_drive_integration', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('oauth_tokens_ibfk_1'), 'oauth_tokens', type_='foreignkey')
    op.create_foreign_key('fk_oauth_tokens_user_id', 'oauth_tokens', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('preferences_ibfk_1'), 'preferences', type_='foreignkey')
    op.create_foreign_key('fk_preferences_user_id', 'preferences', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rate_limiting_ibfk_1'), 'rate_limiting', type_='foreignkey')
    op.create_foreign_key('fk_rate_limiting_user_id', 'rate_limiting', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_refresh_token_session_id'), 'refresh_token', type_='foreignkey')
    op.drop_constraint(op.f('refresh_token_ibfk_1'), 'refresh_token', type_='foreignkey')
    op.create_foreign_key('fk_refresh_token_user_id', 'refresh_token', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_refresh_token_session_id', 'refresh_token', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_session_user_id'), 'session', type_='foreignkey')
    op.create_foreign_key('fk_session_user_id', 'session', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_session_token_session_id'), 'session_token', type_='foreignkey')
    op.drop_constraint(op.f('session_token_ibfk_1'), 'session_token', type_='foreignkey')
    op.create_foreign_key('fk_session_token_user_id', 'session_token', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_session_token_session_id', 'session_token', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('totp_secret_enc_ibfk_1'), 'totp_secret_enc', type_='foreignkey')
    op.create_foreign_key('fk_totp_secret_user_id', 'totp_secret_enc', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_totp_secret_user_id', 'totp_secret_enc', type_='foreignkey')
    op.create_foreign_key(op.f('totp_secret_enc_ibfk_1'), 'totp_secret_enc', 'User', ['user_id'], ['id'])
    op.drop_constraint('fk_session_token_session_id', 'session_token', type_='foreignkey')
    op.drop_constraint('fk_session_token_user_id', 'session_token', type_='foreignkey')
    op.create_foreign_key(op.f('session_token_ibfk_1'), 'session_token', 'User', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_session_token_session_id'), 'session_token', 'session', ['session_id'], ['id'])
    op.drop_constraint('fk_session_user_id', 'session', type_='foreignkey')
    op.create_foreign_key(op.f('fk_session_user_id'), 'session', 'User', ['user_id'], ['id'])
    op.drop_constraint('fk_refresh_token_session_id', 'refresh_token', type_='foreignkey')
    op.drop_constraint('fk_refresh_token_user_id', 'refresh_token', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_token_ibfk_1'), 'refresh_token', 'User', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_refresh_token_session_id'), 'refresh_token', 'session', ['session_id'], ['id'])
    op.drop_constraint('fk_rate_limiting_user_id', 'rate_limiting', type_='foreignkey')
    op.create_foreign_key(op.f('rate_limiting_ibfk_1'), 'rate_limiting', 'User', ['user_id'], ['id'])
    op.drop_constraint('fk_preferences_user_id', 'preferences', type_='foreignkey')
    op.create_foreign_key(op.f('preferences_ibfk_1'), 'preferences', 'User', ['user_id'], ['id'])
    op.drop_constraint('fk_oauth_tokens_user_id', 'oauth_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('oauth_tokens_ibfk_1'), 'oauth_tokens', 'User', ['user_id'], ['id'])
    op.drop_constraint('fk_google_drive_integration_user_id', 'google_drive_integration', type_='foreignkey')
    op.create_foreign_key(op.f('google_drive_integration_ibfk_1'), 'google_drive_integration', 'User', ['user_id'], ['id'])
    op.drop_constraint('fk_email_verification_token_user_id', 'email_verification_token', type_='foreignkey')
    op.create_foreign_key(op.f('email_verification_token_ibfk_1'), 'email_verification_token', 'User', ['user_id'], ['id'])
    op.drop_constraint('fk_backup_configuration_user_id', 'backup_configuration', type_='foreignkey')
    op.create_foreign_key(op.f('backup_configuration_ibfk_1'), 'backup_configuration', 'User', ['user_id'], ['id'])
    op.drop_constraint('fk_zke_encryption_key_user_id', 'ZKE_encryption_key', type_='foreignkey')
    op.create_foreign_key(op.f('ZKE_encryption_key_ibfk_1'), 'ZKE_encryption_key', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
