"""Add uniqueness to unique attributes of user

Revision ID: fdbb247ab912
Revises: b46d9f8cb420
Create Date: 2024-12-04 19:07:38.231652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbb247ab912'
down_revision: Union[str, None] = 'b46d9f8cb420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'User', ['mail'])
    op.create_unique_constraint(None, 'User', ['username'])
    op.create_unique_constraint(None, 'refresh_token', ['hashed_token'])
    op.create_unique_constraint(None, 'session_token', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_token', type_='unique')
    op.drop_constraint(None, 'refresh_token', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    # ### end Alembic commands ###
