name: "zero-totp.com deployment"

permissions:
  contents: read
  packages: write
  deployments: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    tests_and_security:
      name: Tests and security analysis
      uses: ./.github/workflows/security_analysis.yml  # use the callable tests job to run tests
      secrets:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }} 

    docker-frontend:
      needs: [tests_and_security]
      name: Publish Frontend Docker image
      runs-on: ubuntu-latest
      env:
        REPO: zero-totp-frontend
      steps:
        - uses: actions/checkout@v3
        - name: Login to Github
          run : echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.USERNAME_GITHUB }} --password-stdin
        - name: Login to Docker Hub
          run : docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        - name: Create frontend environment file
          working-directory: ./frontend
          run: bash generate-env.sh '${{ github.ref_name }}' '${{secrets.RSA_PUBLIC_KEY}}'
        - name: Generate sitemap.xml
          working-directory: ./frontend
          run: bash generate_sitemap.sh 
        - name: Build Docker image
          working-directory: ./frontend
          run: |
            current_short_version=$(echo ${{ github.ref_name }} | sed -E 's/^v([0-9]+)\.([0-9]+)\.[0-9]+$/\1.\2/') 
            current_long_version=$(echo ${{ github.ref_name }} |  sed -E 's/^v//')
            docker build \
              -t seaweedbrain/$REPO:$current_long_version \
              -t seaweedbrain/$REPO:$current_short_version \
              -t ghcr.io/${{ secrets.USERNAME_GITHUB }}/$REPO:$current_long_version \
              -t ghcr.io/${{ secrets.USERNAME_GITHUB }}/$REPO:$current_short_version . 
        - name: Publish Docker Image to DockerHub
          run: docker push seaweedbrain/$REPO --all-tags
        - name: Publish Docker Image to Github Registry
          run: docker push ghcr.io/${{ secrets.USERNAME_GITHUB }}/$REPO --all-tags
    docker-api:
      needs: [tests_and_security]
      name: Publish API Docker image
      runs-on: ubuntu-latest
      env:
        REPO: zero-totp-api
      steps:
        - uses: actions/checkout@v3
        - name: Login to Github
          run : echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.USERNAME_GITHUB }} --password-stdin
        - name: Login to Docker Hub
          run : docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        - name: Populating API version
          working-directory: ./api
          run: echo ${{ github.ref_name }} > ./VERSION
        - name: Populating API version
          working-directory: ./api
          run: echo ${{ github.ref_name }} > ./VERSION && echo ${{ github.sha}} | cut -c1-7 >> ./VERSION
        - name: Build Docker image
          working-directory: ./api
          run: |
            current_short_version=$(echo ${{ github.ref_name }} | sed -E 's/^v([0-9]+)\.([0-9]+)\.[0-9]+$/\1.\2/') 
            current_long_version=$(echo ${{ github.ref_name }} |  sed -E 's/^v//')
            docker build \
              -t seaweedbrain/$REPO:$current_long_version \
              -t seaweedbrain/$REPO:$current_short_version \
              -t ghcr.io/${{ secrets.USERNAME_GITHUB }}/$REPO:$current_long_version \
              -t ghcr.io/${{ secrets.USERNAME_GITHUB }}/$REPO:$current_short_version . 
        - name: Publish Docker Image to DockerHub
          run: docker push seaweedbrain/$REPO --all-tags
        - name: Publish Docker Image to Github Registry
          run: docker push ghcr.io/${{ secrets.USERNAME_GITHUB }}/$REPO --all-tags

    e2e-tests:
        runs-on: ubuntu-latest
        needs: [docker-frontend, docker-api] 
        name: Run end-to-end tests
        steps:
            - uses: actions/checkout@v4

            - name: Use last published image 
              working-directory: ./e2e-tests
              run: |
                current_version=$(echo ${{ github.ref_name }} | sed 's/^v//')
                echo "Current version: $current_version"
                sed -i "s|\(image: ghcr.io/seaweedbraincy/zero-totp-api:\).*|\1$current_version|" docker-compose.yml
                sed -i "s|\(image: ghcr.io/seaweedbraincy/zero-totp-frontend:\).*|\1$current_version|" docker-compose.yml

            - name: Run e2e docker compose
              uses: hoverkraft-tech/compose-action@v2.0.1
              with:
                compose-file: "./e2e-tests/docker-compose.yml"
            - name: Display current images
              run: docker images
            
            - uses: actions/setup-node@v4
              with:
                node-version: lts/*
            - name: Install dependencies
              working-directory: ./e2e-tests
              run: npm ci
            - name: Install Playwright Browsers
              working-directory: ./e2e-tests
              run: npx playwright install --with-deps
              
            - name: Verify if the API is healthy
              run: |
                response=$(curl -ks https://localhost/api/v1/healthcheck)
                health_status=$(echo "$response" | jq .health)
                if [[ $health_status != '"OK"' ]]; then
                  echo "API is not healthy: $response"
                  docker logs -f --tail 100 api
                  exit 1
                else
                  echo "API is healthy"
                fi
            - name: Run Playwright tests
              working-directory: ./e2e-tests
              run: npx playwright test 
            - uses: actions/upload-artifact@v4
            
              if: ${{ !cancelled() }}
              with:
                name: playwright-report
                path: ./e2e-tests/playwright-report/
                retention-days: 30
    api-docker-security-scan:
      needs: [docker-api]
      name: Scan API Docker image for security vulnerabilities
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install Trivy
          run: |
            sudo apt-get install wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install trivy

        - name: Scan Docker image
          run: |
            current_version=$(echo ${{ github.ref_name }} | sed 's/^v//')
            trivy image --exit-code 1 --severity CRITICAL,HIGH --no-progress --ignore-unfixed ghcr.io/${{ secrets.USERNAME_GITHUB }}/zero-totp-api:$current_version
    frontend-docker-security-scan:
      needs: [docker-frontend]
      name: Scan Frontend Docker image for security vulnerabilities
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install Trivy
          run: |
            sudo apt-get install wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install trivy

        - name: Scan Docker image
          run: |
            current_version=$(echo ${{ github.ref_name }} | sed 's/^v//')
            trivy image --exit-code 1 --severity CRITICAL,HIGH --no-progress --ignore-unfixed ghcr.io/${{ secrets.USERNAME_GITHUB }}/zero-totp-frontend:$current_version
    add-latest-tag-to-docker:
      needs: [e2e-tests, api-docker-security-scan, frontend-docker-security-scan]
      name: Add latest tag to Docker images
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Login to Github
          run : echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.USERNAME_GITHUB }} --password-stdin
        - name: Login to Docker Hub
          run : docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        - name: Add latest tag to Frontend image (ghcr.io)
          run: |
            docker pull ghcr.io/${{ secrets.USERNAME_GITHUB }}/zero-totp-frontend:${{ github.ref_name }}
            docker tag ghcr.io/${{ secrets.USERNAME_GITHUB }}/zero-totp-frontend:${{ github.ref_name }} ghcr.io/${{ secrets.USERNAME_GITHUB }}/zero-totp-frontend:latest
            docker push ghcr.io/${{ secrets.USERNAME_GITHUB }}/zero-totp-frontend:latest
        - name: Add latest tag to Frontend image (Docker Hub)
          run: |
            docker pull seaweedbrain/zero-totp-frontend:${{ github.ref_name }}
            docker tag seaweedbrain/zero-totp-frontend:${{ github.ref_name }} seaweedbrain/zero-totp-frontend:latest
            docker push seaweedbrain/zero-totp-frontend:latest
        - name: Add latest tag to API image
          run: |
            docker pull ghcr.io/${{ secrets.USERNAME_GITHUB }}/zero-totp-api:${{ github.ref_name }}
            docker tag ghcr.io/${{ secrets.USERNAME_GITHUB }}/zero-totp-api:${{ github.ref_name }} ghcr.io/${{ secrets.USERNAME_GITHUB }}/zero-totp-api:latest
            docker push ghcr.io/${{ secrets.USERNAME_GITHUB }}/zero-totp-api:latest
        - name: Add latest tag to API image (Docker Hub)
          run: |
            docker pull seaweedbrain/zero-totp-api:${{ github.ref_name }}
            docker tag seaweedbrain/zero-totp-api:${{ github.ref_name }} seaweedbrain/zero-totp-api:latest
            docker push seaweedbrain/zero-totp-api:latest
    deploy-production-sw:
       needs: [add-latest-tag-to-docker]
       name: Deploy on production server (SW)
       environment: 
        name: Production (SW)
        url: https://sw.zero-totp.com
       runs-on: ubuntu-latest
       steps:
         - name: SW deployment
           uses: distributhor/workflow-webhook@v3
           env:
             webhook_url: ${{ secrets.WEBHOOK_URL_SW }}
    deploy-production-ca:
        needs: add-latest-tag-to-docker]
        name: Deploy on production server (CANADA)
        environment: 
           name: Production (CANADA)
           url: https://ca.zero-totp.com
        runs-on: ubuntu-latest
        steps:
          - name: CA deployment
            uses: distributhor/workflow-webhook@v3
            env:
              webhook_url: ${{ secrets.WEBHOOK_URL_CA }}
    deploy-production-themis:
        needs: [add-latest-tag-to-docker]
        name: Deploy on production server (THEMIS)
        environment: 
           name: Production (THEMIS)
           url: https://themis.zero-totp.com
        runs-on: ubuntu-latest
        steps:
          - name: TH deployment
            uses: distributhor/workflow-webhook@v3
            env:
              webhook_url: ${{ secrets.WEBHOOK_URL_TH }}

        
