name: "Run end-to-end tests"


on: 
    workflow_call:
      secrets:
        SONAR_TOKEN:
          required: true
        SONAR_HOST_URL:
          required: true
        GITGUARDIAN_API_KEY:
          required: true
        TOKEN_GITHUB:
          required: true
        USERNAME_GITHUB:
            required: true
        DEV_RSA_PUBLIC_KEY:
            required: true
        

jobs:
    docker_images_published:
        uses: ./.github/workflows/build_and_publish_docker.yml
        secrets:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
    e2e-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Run e2e docker compose
              uses: hoverkraft-tech/compose-action@v2.0.1
              with:
                compose-file: "./e2e-tests/docker-compose.yml"
            
            - uses: actions/setup-node@v4
              with:
                node-version: lts/*
            - name: Install dependencies
              working-directory: ./e2e-tests
              run: npm ci
            - name: Install Playwright Browsers
              working-directory: ./e2e-tests
              run: npx playwright install --with-deps
            - name: Add DNS entry to /etc/hosts
              run: |
                echo "127.0.0.1 zero-totp.lan" | sudo tee -a /etc/hosts
                cat /etc/hosts
            - name: Run Playwright tests
              working-directory: ./e2e-tests
              run: npx playwright test 
            - uses: actions/upload-artifact@v4
            
              if: ${{ !cancelled() }}
              with:
                name: playwright-report
                path: ./e2e-tests/playwright-report/
                retention-days: 30