name: "Sonarqube Security Scan"

permissions:
  contents: read


on: 
    pull_request:
        branches:
          - main
    workflow_call:
      secrets:
        SONAR_TOKEN:
          required: true
        SONAR_HOST_URL:
          required: true
        GITGUARDIAN_API_KEY:
          required: true
        MAXMIND_PERMALINK:
          required: true

jobs:
  tests:
    uses: ./.github/workflows/test.yml  #
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
      MAXMIND_PERMALINK: ${{ secrets.MAXMIND_PERMALINK }}
  sonarqube:
    needs: [tests]
    name: SonarQube scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Sonar scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
